# Generated by Django 4.2.30 on 2026-07-07 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0002_photo_google_drive_file_id_photo_image_url_and_more'),
        ('Events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FaceEngine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HDRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent')], default='PENDING', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hd_requests', to='Events.event')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hd_requests', to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hd_requests', to='Photos.photo')),
            ],
            options={
                'unique_together': {('guest', 'photo')},
            },
        ),
    ]
