# Generated by Django 4.2.18 on 2026-07-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_googledrivecredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='selfie_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
