# Generated by Django 4.2.18 on 2026-07-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_userprofile_business_name_userprofile_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True),
        ),
    ]
