# Generated by Django 4.2.18 on 2026-07-26 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_collection'),
        ('Photos', '0002_photo_google_drive_file_id_photo_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='Events.collection'),
        ),
    ]
